name: food_delivery
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.3.2
  easy_localization: ^3.0.0
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter

  flutter_native_splash: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/

flutter_native_splash:
  color: "#e6dcc1"
  image: assets/images/splash.jpeg
  branding: assets/images/splash.jpeg
  android: true
  ios: true
  fullscreen: true
